package reader;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;

import mod.Mod;

/**
 * ModFileReader implementation for reading the modlist file generated by 
 * Mod Organizer for its profiles.
 * 
 * @author Michael Bogochow
 * @since June 21, 2014
 * @version 1.0.0
 */
public class ModListFileReader implements ModFileReader
{
  @Override
  public List<Mod> readFile(String fileName) throws FileNotFoundException
  {
    List<Mod> modList = new LinkedList<>();
    
    try (BufferedReader br = new BufferedReader(new FileReader(fileName)))
    {
      // Skip the first line since Mod Organizer leaves a comment on the first 
      // line of its mod list file
      br.readLine();
      
      for (String line = br.readLine(); line != null; line = br.readLine())
      {
        Mod mod = new Mod(line.substring(1));
        mod.setEnabled(line.charAt(0) == '+' ? true : false);
        modList.add(mod);
      }
    }
    catch (IOException e)
    {
      // TODO Auto-generated catch block
      e.printStackTrace();
    }
    
    return modList;
  } /* readFile */
}
