package writer;

import java.io.File;
import java.io.IOException;

import mod.Mod;

public final class ModOrganizerModWriter extends SimpleModWriter
{
  private static final String initString = "# This file was automatically generated by Mod Organizer."
      + System.lineSeparator();
  private static final String EnabledPrefix = "+";
  private static final String DisabledPrefix = "-";

  public ModOrganizerModWriter(String filePath) throws IOException
  {
    super(filePath);
  }

  public ModOrganizerModWriter(File file) throws IOException
  {
    super(file);
  }

  @Override
  public void writeHeader() throws IOException
  {
    writer.write(initString);
  }

  @Override
  public void writeMod(Mod mod) throws IOException
  {
    String prefix = mod.isEnabled() ? EnabledPrefix : DisabledPrefix;
    writer.write(prefix + mod.getName() + System.lineSeparator());
  }
}
